### ISSUE TITLE
NPE in the converter

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#34]
I got this error when transforming some Java code:

I think it might have happened with a `super(x, y);` call, IIRC.

```

null
java.lang.NullPointerException
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitArgumentList(JavaToCeylonConverter.java:1170)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitConstructorDeclaration(JavaToCeylonConverter.java:598)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitConstructorDeclaration(JavaToCeylonConverter.java:16)
	at ceylon.tool.converter.java2ceylon.Java8Parser$ConstructorDeclarationContext.accept(Java8Parser.java:6264)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitClassBodyDeclaration(Java8BaseVisitor.java:370)
	at ceylon.tool.converter.java2ceylon.Java8Parser$ClassBodyDeclarationContext.accept(Java8Parser.java:3645)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitClassBody(Java8BaseVisitor.java:363)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitClassBody(JavaToCeylonConverter.java:318)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitNormalClassDeclaration(JavaToCeylonConverter.java:216)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitNormalClassDeclaration(JavaToCeylonConverter.java:16)
	at ceylon.tool.converter.java2ceylon.Java8Parser$NormalClassDeclarationContext.accept(Java8Parser.java:3114)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitClassDeclaration(Java8BaseVisitor.java:307)
	at ceylon.tool.converter.java2ceylon.Java8Parser$ClassDeclarationContext.accept(Java8Parser.java:3042)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitClassMemberDeclaration(Java8BaseVisitor.java:377)
	at ceylon.tool.converter.java2ceylon.Java8Parser$ClassMemberDeclarationContext.accept(Java8Parser.java:3724)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitClassBodyDeclaration(Java8BaseVisitor.java:370)
	at ceylon.tool.converter.java2ceylon.Java8Parser$ClassBodyDeclarationContext.accept(Java8Parser.java:3645)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitClassBody(Java8BaseVisitor.java:363)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitClassBody(JavaToCeylonConverter.java:318)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitNormalClassDeclaration(JavaToCeylonConverter.java:216)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitNormalClassDeclaration(JavaToCeylonConverter.java:16)
	at ceylon.tool.converter.java2ceylon.Java8Parser$NormalClassDeclarationContext.accept(Java8Parser.java:3114)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitClassDeclaration(Java8BaseVisitor.java:307)
	at ceylon.tool.converter.java2ceylon.Java8Parser$ClassDeclarationContext.accept(Java8Parser.java:3042)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitTypeDeclaration(Java8BaseVisitor.java:300)
	at ceylon.tool.converter.java2ceylon.Java8Parser$TypeDeclarationContext.accept(Java8Parser.java:2976)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitCompilationUnit(Java8BaseVisitor.java:244)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitCompilationUnit(JavaToCeylonConverter.java:173)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitCompilationUnit(JavaToCeylonConverter.java:16)
	at ceylon.tool.converter.java2ceylon.Java8Parser$CompilationUnitContext.accept(Java8Parser.java:2447)
	at org.intellij.plugins.ceylon.ide.action.PasteJavaToCeylonAction.transformJavaToCeylon$priv$(PasteJavaToCeylonAction.ceylon:120)
	at org.intellij.plugins.ceylon.ide.action.PasteJavaToCeylonAction.access$000(PasteJavaToCeylonAction.ceylon:65)
	at org.intellij.plugins.ceylon.ide.action.PasteJavaToCeylonAction$1anonymous_0_.run(PasteJavaToCeylonAction.ceylon:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rohitmohan96** [comment]
This should also be fixed now.

**Comment by gavinking** [comment]
Thanks.
