### ISSUE TITLE
NPE in converter

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#36]
I tried to paste this admittedly bogus "Java" code:

    void fun(Object arg) => print(arg.toString());

And got the following NPE:

```
null
java.lang.NullPointerException
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitFormalParameterList(JavaToCeylonConverter.java:407)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitMethodDeclarator(JavaToCeylonConverter.java:381)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitMethodHeader(JavaToCeylonConverter.java:357)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitMethodDeclaration(JavaToCeylonConverter.java:342)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitMethodDeclaration(JavaToCeylonConverter.java:16)
	at ceylon.tool.converter.java2ceylon.Java8Parser$MethodDeclarationContext.accept(Java8Parser.java:5026)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
	at ceylon.tool.converter.java2ceylon.Java8BaseVisitor.visitCompilationUnit(Java8BaseVisitor.java:244)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitCompilationUnit(JavaToCeylonConverter.java:173)
	at ceylon.tool.converter.java2ceylon.JavaToCeylonConverter.visitCompilationUnit(JavaToCeylonConverter.java:16)
	at ceylon.tool.converter.java2ceylon.Java8Parser$CompilationUnitContext.accept(Java8Parser.java:2447)
	at org.intellij.plugins.ceylon.ide.action.PasteJavaToCeylonAction.transformJavaToCeylon$priv$(PasteJavaToCeylonAction.ceylon:120)
	at org.intellij.plugins.ceylon.ide.action.PasteJavaToCeylonAction.access$000(PasteJavaToCeylonAction.ceylon:65)
	at org.intellij.plugins.ceylon.ide.action.PasteJavaToCeylonAction$1anonymous_0_.run(PasteJavaToCeylonAction.ceylon:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gavinking** [comment]
Fixed.
